<a href="https://colab.research.google.com/github/PratikMBhoud/python-1/blob/main/DATA_PREPROCESSING_TEMPLETE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

#import data Set
dataset=pd.read_csv('/content/Data.csv')
dataset.head()
dataset.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [3]:
dataset.describe()


Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [4]:
#independent and Dependent variable
X = dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values

In [5]:
#Handling Missing data 

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer = imputer.fit(X[:, 1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [6]:
#Encoding independent Variable 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
#Encoding Catagorical data- Dependent Variable
from sklearn.preprocessing import LabelEncoder
label_y=LabelEncoder()
y=label_y.fit_transform(y)

In [8]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [10]:
#splitting  the  dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)
X_train

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [11]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [12]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [13]:
y_test

array([0, 0])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=125)

In [15]:
X_train

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0]], dtype=object)

In [16]:
X_test

array([[1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [17]:
y_test

array([1, 1])

In [18]:
y_train

array([0, 0, 1, 1, 0, 0, 1, 0])

In [22]:
  #feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train= sc_X.fit_transform(X_train)
X_test= sc_X.fit_transform(X_test)
X_train


array([[ 1.29099445, -0.77459667, -0.57735027,  0.5678988 ,  0.61885324],
       [-0.77459667, -0.77459667,  1.73205081, -0.27277029, -1.24158238],
       [-0.77459667,  1.29099445, -0.57735027, -0.07601795, -0.14599252],
       [ 1.29099445, -0.77459667, -0.57735027, -0.88091389, -0.68345169],
       [-0.77459667, -0.77459667,  1.73205081, -0.39797633, -0.40438635],
       [-0.77459667,  1.29099445, -0.57735027,  1.53377393,  1.64209282],
       [ 1.29099445, -0.77459667, -0.57735027,  1.21181555,  1.2700057 ],
       [-0.77459667,  1.29099445, -0.57735027, -1.68580983, -1.05553882]])

In [23]:
X_test

array([[ 1.,  0., -1.,  1.,  1.],
       [-1.,  0.,  1., -1., -1.]])